[package]
name = "aureonoise"
version = "0.1.0"
edition = "2021"
authors = ["Alessio Ivoyce Cazzaniga"]
description = "aureonoise~ DSP engine in Rust with Python bindings"
license = "MIT"

[lib]
name = "aureonoise"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
rand = "0.8"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.dev]
opt-level = 1
